export const GET_MOVIES_PREMIERS_DATA = 'GET_MOVIES_PREMIERS_DATA';
export const GET_MOVIES_PREMIERS_DATA_ERROR = 'GET_MOVIES_PREMIERS_DATA_ERROR'
export const GET_MOVIES_PREMIERS_DATA_LOADING = 'GET_MOVIES_PREMIERS_DATA_LOADING'