export const GET_TV_PREMIERS_DATA = 'GET_TV_PREMIERS_DATA';
export const GET_TV_PREMIERS_DATA_ERROR = 'GET_TV_PREMIERS_DATA_ERROR'
export const GET_TV_PREMIERS_DATA_LOADING = 'GET_TV_PREMIERS_DATA_LOADING'