export const GET_USER_MOVIES_PREMIERS_DATA = 'GET_USER_MOVIES_PREMIERS_DATA';
export const GET_USER_MOVIES_PREMIERS_DATA_ERROR = 'GET_USER_MOVIES_PREMIERS_DATA_ERROR'
export const GET_USER_MOVIES_PREMIERS_DATA_LOADING = 'GET_USER_MOVIES_PREMIERS_DATA_LOADING'
export const ADD_MOVIE_TO_LIST = 'ADD_MOVIE_TO_LIST'